[package]
name = "kv-search-native"
version = "0.1.0"
edition = "2024"

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.29.0"
pyo3 = { version = "0.29.0", features = ["abi3-py313"] }
qdrant-edge = { package = "edge", git = "https://github.com/qdrant/qdrant.git", rev = "2ef887bae1e840b7b3bceb9b94b23589eaff4693" }
rayon = "1.12.0"

[profile.release]
lto = true
codegen-units = 1
