[project]
name = "kv-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.14.0",
    "causal-conv1d ; sys_platform == 'linux'",
    "datasets>=4.8.5",
    "flash-attn>=2.8.3.post1; sys_platform == 'linux'",
    "flash-linear-attention>=0.5.1 ; sys_platform == 'linux'",
    "matplotlib>=3.11.0",
    "mistral-common>=1.11.3",
    "pillow>=12.2.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "qdrant-client>=1.18.0",
    "qdrant-edge-py>=0.7.2",
    "safetensors>=0.7.0",
    "torch>=2.12.0",
    "torchvision>=0.27.0",
    "transformers>=5.9.0",
]

[project.scripts]
kv-search = "kv_search.main:main"

[build-system]
requires = ["maturin>=1.14,<2"]
build-backend = "maturin"

[tool.uv]
no-build-isolation-package = ["flash-attn", "causal-conv1d"]
extra-build-dependencies = { flash-attn = ["ninja"], causal-conv1d = ["ninja"] }
# This is somewhat nvidia spark specific but whatever
extra-build-variables = { flash-attn = { MAX_JOBS = "16", FLASH_ATTN_CUDA_ARCHS = "120" }, causal-conv1d = { MAX_JOBS = "16" } }

[tool.maturin]
module-name = "kv_search._native"

[dependency-groups]
dev = [
    "ipython>=9.16.1",
    "jupytext>=1.19.5",
    "maturin>=1.14.1",
    "ninja>=1.13.0",
]
